# Generated by Django 4.1.5 on 2023-04-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remail', models.CharField(max_length=100)),
                ('rpassword', models.CharField(max_length=100)),
            ],
        ),
    ]
