# Generated by Django 4.2.5 on 2023-11-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='remail',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='rpassword',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='register',
            table='UserRegistration',
        ),
    ]
